<?php

namespace App\Filament\Resources\OtherPageResource\Pages;

use App\Filament\Resources\OtherPageResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListOtherPages extends ListRecords
{
    protected static string $resource = OtherPageResource::class;

    protected function getActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): Builder
    {
        return parent::getTableQuery()->where('type', 'other_pages'); // TODO: Change the autogenerated stub
    }
}
