<?php

namespace App\Filament\Resources\HomeFieldResource\Pages;

use App\Filament\Resources\HomeFieldResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListHomeFields extends ListRecords
{
    protected static string $resource = HomeFieldResource::class;

    protected function getActions(): array
    {
        return [
//            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): Builder
    {
        return parent::getTableQuery()->where('type', 'homeFields'); // TODO: Change the autogenerated stub
    }
}
